---
# Install & configure Prometheus (uses templates/prometheus.yml.j2)

- name: Create prometheus user
  user:
    name: prometheus
    system: yes
    shell: /sbin/nologin

- name: Create Prometheus config directory
  file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0755"

- name: Create Prometheus data directory
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0755"

- name: Download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz
    mode: "0644"

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes
    creates: /opt/prometheus-2.52.0.linux-amd64

- name: Install Prometheus binaries
  copy:
    src: "/opt/prometheus-2.52.0.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: "0755"
    remote_src: yes
  loop:
    - prometheus
    - promtool

- name: Deploy Prometheus config from template
  template:
    src: prometheus.yml.j2         # ← MUST live in roles/prometheus/templates/
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: "0644"
  notify: Restart Prometheus

- name: Install systemd unit
  copy:
    dest: /etc/systemd/system/prometheus.service
    mode: "0644"
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      User=prometheus
      Group=prometheus
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus \
        --web.listen-address=:9090
      Restart=always

      [Install]
      WantedBy=multi-user.target
  notify: Daemon Reload

- name: Ensure Prometheus service enabled and running
  systemd:
    name: prometheus
    enabled: yes
    state: started

